# Generated by Django 4.2.11 on 2026-04-22 09:47

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tiers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_operation', models.DateField(verbose_name='Date')),
                ('nature', models.CharField(choices=[('ENTREE', 'Entrée'), ('DEPENSE', 'Dépense')], max_length=7, verbose_name='Nature')),
                ('tiers_libre', models.CharField(blank=True, default='', max_length=200, verbose_name='Tiers libre')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Montant')),
                ('commentaire', models.TextField(blank=True, default='', verbose_name='Commentaire')),
                ('mois', models.PositiveSmallIntegerField(verbose_name='Mois')),
                ('annee', models.PositiveIntegerField(verbose_name='Année')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operations_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operations_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Supprimé par')),
                ('tiers', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='tiers.tiers', verbose_name='Tiers')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operations_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'Opération',
                'verbose_name_plural': 'Opérations',
                'db_table': 'operations',
                'ordering': ['date_operation', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='SoldeMois',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.PositiveSmallIntegerField(verbose_name='Mois')),
                ('annee', models.PositiveIntegerField(verbose_name='Année')),
                ('solde_reporte', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Solde reporté')),
                ('total_entrees', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Total entrées')),
                ('total_depenses', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Total dépenses')),
                ('solde_final', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Solde final')),
                ('is_cloture', models.BooleanField(default=False, verbose_name='Clôturé')),
                ('cloture_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cloture_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clotures', to=settings.AUTH_USER_MODEL, verbose_name='Clôturé par')),
            ],
            options={
                'verbose_name': 'Solde du mois',
                'verbose_name_plural': 'Soldes des mois',
                'db_table': 'soldes_mois',
                'ordering': ['-annee', '-mois'],
                'unique_together': {('mois', 'annee')},
            },
        ),
    ]
