# Generated by Django 4.2.11 on 2026-04-22 09:47

import apps.fichiers.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PieceJointe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to=apps.fichiers.models.upload_piece_jointe, verbose_name='Fichier')),
                ('nom_original', models.CharField(max_length=255, verbose_name='Nom original')),
                ('taille', models.PositiveIntegerField(verbose_name='Taille (octets)')),
                ('mime_type', models.CharField(max_length=100, verbose_name='Type MIME')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('operation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='piece_jointe', to='operations.operation', verbose_name='Opération')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pieces_jointes', to=settings.AUTH_USER_MODEL, verbose_name='Uploadé par')),
            ],
            options={
                'verbose_name': 'Pièce jointe',
                'verbose_name_plural': 'Pièces jointes',
                'db_table': 'pieces_jointes',
            },
        ),
    ]
