# Generated by Django 4.2.11 on 2026-04-26 18:47

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom')),
                ('programme', models.CharField(choices=[('INFORMATIQUE', 'Programme Informatique & Management'), ('HUMANITAIRE', 'Programme Action Humanitaire')], max_length=20, verbose_name='Programme')),
                ('duree', models.CharField(blank=True, max_length=100, verbose_name='Durée')),
                ('prix_base', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Prix de base (FCFA)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Formation',
                'verbose_name_plural': 'Formations',
                'db_table': 'formations',
                'ordering': ['programme', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=20, unique=True, verbose_name='N° inscription')),
                ('civilite', models.CharField(choices=[('M', 'M.'), ('MME', 'Mme'), ('MLLE', 'Mlle')], max_length=5, verbose_name='Civilité')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=200, verbose_name='Prénom(s)')),
                ('date_naissance', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('lieu_naissance', models.CharField(blank=True, max_length=200, verbose_name='Lieu de naissance')),
                ('telephone', models.CharField(max_length=50, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('nationalite', models.CharField(blank=True, default='Burkinabè', max_length=100, verbose_name='Nationalité')),
                ('ville', models.CharField(blank=True, max_length=100, verbose_name='Ville')),
                ('quartier', models.CharField(blank=True, max_length=100, verbose_name='Quartier')),
                ('secteur', models.CharField(blank=True, max_length=50, verbose_name='Secteur')),
                ('cnib_numero', models.CharField(blank=True, max_length=50, verbose_name='N° CNIB')),
                ('cnib_date', models.DateField(blank=True, null=True, verbose_name='Date CNIB')),
                ('cnib_lieu', models.CharField(blank=True, max_length=100, verbose_name='Lieu CNIB')),
                ('contact_urgence_nom', models.CharField(blank=True, max_length=200, verbose_name='Contact urgence — Nom')),
                ('contact_urgence_tel', models.CharField(blank=True, max_length=50, verbose_name='Contact urgence — Tél')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='inscriptions/photos/', verbose_name='Photo')),
                ('centre', models.CharField(choices=[('OUAGA', 'EPA Ouagadougou'), ('BOBO', 'EPA Bobo'), ('SAHEL', 'EPA Sahel/Dori')], max_length=10, verbose_name='Centre')),
                ('option_cours', models.CharField(choices=[('JOUR', 'Jour'), ('SOIR', 'Soir'), ('EN_LIGNE', 'En ligne')], max_length=10, verbose_name='Option cours')),
                ('niveau_etude', models.CharField(blank=True, choices=[('BEPC', 'BEPC'), ('BAC', 'BAC'), ('BAC_PLUS', 'BAC+'), ('LICENCE', 'Licence'), ('M1_M2', 'M1/M2')], max_length=20, verbose_name="Niveau d'étude")),
                ('statut_professionnel', models.CharField(blank=True, choices=[('EMPLOYE_TP', 'Employé à temps plein'), ('FREELANCE', 'Employé en free-lance'), ('STAGIAIRE', 'Stagiaire'), ('ENTREPRENEUR', 'Entrepreneur'), ('ETUDIANT', 'Étudiant(e)'), ('AUTRE', 'Autre')], max_length=20, verbose_name='Statut professionnel')),
                ('nom_employeur', models.CharField(blank=True, max_length=200, verbose_name='Employeur')),
                ('projet_apres_formation', models.TextField(blank=True, verbose_name='Projet après formation')),
                ('qui_paye', models.CharField(choices=[('MOI_MEME', 'Moi-même'), ('PARRAIN', 'Mon parrain'), ('ENTREPRISE', 'Mon Entreprise/Association/ONG')], default='MOI_MEME', max_length=20, verbose_name='Qui paye')),
                ('montant_formation', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant formation (FCFA)')),
                ('bourse_pourcentage', models.PositiveSmallIntegerField(choices=[(0, '0%'), (5, '5%'), (10, '10%'), (15, '15%'), (20, '20%'), (25, '25%'), (30, '30%'), (35, '35%'), (40, '40%'), (45, '45%'), (50, '50%')], default=0, verbose_name='Bourse (%)')),
                ('frais_inscription', models.DecimalField(decimal_places=2, default=Decimal('15000.00'), max_digits=12, verbose_name="Frais d'inscription (FCFA)")),
                ('nombre_tranches', models.PositiveSmallIntegerField(choices=[(1, '1 tranche'), (2, '2 tranches'), (3, '3 tranches')], default=1, verbose_name='Nombre de tranches')),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('SOLDE', 'Soldé'), ('ABANDON', 'Abandon')], default='EN_COURS', max_length=20, verbose_name='Statut')),
                ('date_inscription', models.DateField(default=django.utils.timezone.now, verbose_name="Date d'inscription")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscriptions_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscriptions', to='formations.formation', verbose_name='Formation')),
            ],
            options={
                'verbose_name': 'Inscription',
                'verbose_name_plural': 'Inscriptions',
                'db_table': 'inscriptions',
                'ordering': ['-date_inscription', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_payeur', models.CharField(choices=[('PARRAIN', 'Parrain'), ('ENTREPRISE', 'Entreprise / ONG')], max_length=20, verbose_name='Type')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom')),
                ('telephone', models.CharField(blank=True, max_length=50, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Payeur',
                'verbose_name_plural': 'Payeurs',
                'db_table': 'payeurs',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Tranche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField(verbose_name='N° tranche')),
                ('montant_attendu', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant attendu')),
                ('date_echeance', models.DateField(verbose_name="Date d'échéance")),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('PAYE', 'Payé'), ('EN_RETARD', 'En retard')], default='EN_ATTENTE', max_length=15, verbose_name='Statut')),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tranches', to='formations.inscription', verbose_name='Inscription')),
            ],
            options={
                'verbose_name': 'Tranche',
                'verbose_name_plural': 'Tranches',
                'db_table': 'tranches',
                'ordering': ['inscription', 'numero'],
                'unique_together': {('inscription', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='Versement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_versement', models.CharField(choices=[('FRAIS_INSCRIPTION', "Frais d'inscription"), ('TRANCHE', 'Tranche')], max_length=20, verbose_name='Type')),
                ('numero_recu', models.CharField(editable=False, max_length=30, unique=True, verbose_name='N° reçu')),
                ('date_versement', models.DateField(verbose_name='Date')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant (FCFA)')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versements_created', to=settings.AUTH_USER_MODEL, verbose_name='Caissier')),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versements', to='formations.inscription', verbose_name='Inscription')),
                ('operation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versement_formation', to='operations.operation', verbose_name='Opération caisse')),
                ('tranche', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versements', to='formations.tranche', verbose_name='Tranche')),
            ],
            options={
                'verbose_name': 'Versement',
                'verbose_name_plural': 'Versements',
                'db_table': 'versements',
                'ordering': ['-date_versement', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='inscription',
            name='payeur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inscriptions', to='formations.payeur', verbose_name='Payeur'),
        ),
    ]
